### ISSUE TITLE
Suggested Methods and Bugs

### ISSUE THREAD

**Issue by wikiro** [branflake2267/GWT-Maps-V3-Api#123]
1. no method "setCenter(lng, zoom)" in class MapWidget
2. setMap(null) -> two methods in class (conflict)
   com\google\gwt\maps\client\overlays\Marker.java
3. Circle - no method "setCenter(lng)"

``` java
public void setCenter(LatLng center) {  <--- doesn't work this method
        CircleOptions options = CircleOptions.newInstance();
        options.setFillColor(FILL_COLOR);
        options.setCenter(center);
        options.setStrokeWeight(4);
        options.setStrokeColor(LINE_COLOR);
        options.setRadius(circle.getRadius());
        circle.setOptions(options);       
    }
```
1. Polyline - there is no event like "addPolylineLineUpdatedHandler" (when vertex was moved to some place while editing)

**Comment by branflake2267** [comment]
Thanks for reporting! I'll get on this asap. :)

**Comment by branflake2267** [comment]
For marker instead of using setMap(null) try marker.close() or marker.clear()

Yeah, setMap((MapWidget) null) might be needed. I'll see if there is another option.

**Comment by wikiro** [comment]
ok. thank you. if i find another bugs i will post here.

**Comment by twistedpair** [comment]
FYI, since Java needs to know the parameter type for method overloading, the following works as well:

``` java
MapWidget widget = null;
myObj.setMap(widget);
```

Also, some of the proposed methods are not in the [Official JS API](https://developers.google.com/maps/documentation/javascript/reference#Map) such as `setCenter(lng, zoom)`. Generally, this project is a wrapper to GWT access to the JS API, so it mirrors the methods available there, rather than adding new ones, unless there is a JS/Java language impedance mismatch.

**Comment by wikiro** [comment]
twistedpair, why you think so? i think we should add all usefull methods. In version gwt maps api 2 there were a lot of like this

**Comment by twistedpair** [comment]
@evmx Good point. You are correct that Google has deprecated some functionality from V2. I merely mean that we try to keep up with the official release notes and API so that we know when we're done.

**Comment by wikiro** [comment]
_Polyline - there is no event like "addPolylineLineUpdatedHandler" (when vertex was moved to some place while editing)_

how create this event, help me please

**Comment by branflake2267** [comment]
Would it be possible to have you start a new issue for that question?

**Comment by wikiro** [comment]
ok. here is it 
https://github.com/branflake2267/GWT-Maps-V3-Api/issues/132

**Comment by branflake2267** [comment]
I won't add the setCenter(lng, zoom) b/c those methods exists individually and its my goal to follow the js api as close as possible due to time and bandwidth I have. I'm always open to fork and pull request with modifications and would consider the add. 

I fixing circle and poloyline has its own issue. 

The setMap(null) has method overloading and type designation fixes overloading with null.

Closing this issue b/c the items either exist or have there own issue.
