### ISSUE TITLE
clear all overlays

### ISSUE THREAD

**Issue by bhamid** [branflake2267/GWT-Maps-V3-Api#16]
Hi 
I Thank You for your answers, I have another problem:
is there a method to clear the map and delete all overlays ?

**Comment by twistedpair** [comment]
bhamid,

There is no method like that. The methods on the [Maps Javascript API](https://developers.google.com/maps/documentation/javascript/reference#Map) have no such method. The issue here is that you add overlay items to a map using the setMap() method of the overlay, rather than something like map.addOverlay(overlay). So, even it we added a list of non-removed overlays inside the MapWidget class, we would not know what is on the map, since they are not added that way.

Typically you would work around this by keeping a tracking array, list, or map of the things you've added to the map and adding/removing them from the tracking list as you add/remove them from the map. This way you can write a clear() method that just runs down this list and clears everything off the map. That is how I've done this in my apps.

**Comment by kuldeeps160** [comment]
Thanks for your suggestions.
its works great for me.
