### ISSUE TITLE
Marker class could implement HasClickHandlers interface

### ISSUE THREAD

**Issue by povilasb** [branflake2267/GWT-Maps-V3-Api#209]
As the topic mentions [Marker](https://github.com/branflake2267/GWT-Maps-V3-Api/blob/master/gwt-maps-api/src/main/java/com/google/gwt/maps/client/overlays/Marker.java) could implement standard gwt interface [HasClickHandlers](http://www.gwtproject.org/javadoc/latest/com/google/gwt/event/dom/client/HasClickHandlers.html).

**Comment by twistedpair** [comment]
Thanks for the suggestion @povilasb .

`Marker` does not use `ClickHandler`, but rather `MapHandler<E> handler`. In order to comply with `HasClickHandlers` we'd need to revamp the underlying click handing, registration and unregistration code.

Since all handlers must be passed to 

``` javascript
google.maps.event.addListener(instance:Object, eventName:string, handler:Function)
```

There is no certainty that all implementations of `ClickHandler` would be recognized by the GMaps implementation. Accordingly, I don't think we should use the generic GWT handlers, as that would imply we support all implementations of them, while we actually would not.
