### ISSUE TITLE
No tags in GitHub

### ISSUE THREAD

**Issue by martinlong1978** [branflake2267/GWT-Maps-V3-Api#27]
Hi, 

I assume you have tags in your local repo for "v3-3.8.0-beta1", for example. Could you push these to Github? It would make it easier to see if we have a particular fix in our version, and see what has changed etc. 

Thanks

Martin

**Comment by twistedpair** [comment]
Yes, as you can see I'm a busy bee this week. I'll:
- [done] Put up the Javadocs in the gh-pages
- [done] Rebuild the jars and put them up hosted on gh-pages
- [in progress] Work on getting things moved to gh or mvn central
- [done] Update the Demo with a number of new GMaps 3.9 features
- [done] Use more branches for 3.9 dev (currently in trunk, not best practice)
- [done] Pushing tags to gh for builds

There is currently an issue for the 3.8/9 feature update. I'm working to close that and finding various things to clean up along the way. You can already see the new Transit/Traffic/Weather layers in the [showcase](http://gonevertical-apis.appspot.com/).

**Comment by martinlong1978** [comment]
Brilliant. Thanks for the update. It really is a great API.

**Comment by twistedpair** [comment]
Pushed the tags over. Frankly I suggest the beta2 branch as it builds delightfully with Maven. The only reason it is 'beta' is that I've not gotten 100% of the API ported. There are some small bits (that you've probably never heard of) that are not quite there yet. I've got to go through the 3.8 API page and check everyone off an ensure it's done. Then I'll drop the beta.

That being said, I'm now going to work to the 3.9 tag since as of this last week it's the current official release branch according the the Google Maps API team (3.10 is experimental). That's where I'll finalize the Heatmaps and Weather items. It's worth nothing that they are adding to the API all the time, so stay abreast of their release notes if you're a real fan.

Sing out if you have any issues in 3.8 and I'll patch them up lickity split.
