### ISSUE TITLE
MapCanvasProjection.fromLatLngToDivPixel return void instead of Point

### ISSUE THREAD

**Issue by sonytricoire** [branflake2267/GWT-Maps-V3-Api#64]
From GMaps Javascript API, the methode signature is :

Point [MapCanvasProjection](https://developers.google.com/maps/documentation/javascript/reference#MapCanvasProjection).fromLatLngToDivPixel(LatLng) 

In your API the [method](https://github.com/branflake2267/GWT-Maps-V3-Api/blob/master/Apis_Google_Maps/src/com/google/gwt/maps/client/overlays/MapCanvasProjection.java) returns Void. Why ?

**Comment by twistedpair** [comment]
This appears to be a defect. This will be rectified shortly and we'll update this Issue. Thanks for reporting this.

**Comment by twistedpair** [comment]
Fixed this partially in 38268807d0d84defc971ef162e2a4e2b49b23973. 

Noticed 3 [OverlayView](https://developers.google.com/maps/documentation/javascript/reference#OverlayView) methods are not implemented by GMaps at all, but you need to implement then as prototypes in your JSO.

We need to add either handlers or a Callback wrapper so the users can set their own implementations for
- `OverlayView.draw()`
- `OverlayView.onAdd()`
- `OverlayView.onRemove()`

I added tests for them in the spirit of TDD that will pass once we've got this in their.

Also, the following two methods fail in GWTTestCase. I don't know whey since the other two work fine. This needs further investigation.
- `MapCanvasProjection.fromContainerPixelToLatLng()`
- `MapCanvasProjection.fromLatLngToDivPixel()`

**Comment by branflake2267** [comment]
Nice. I can help take a look next week. I aim to get some more time in at working on some of these issues too. :)

**Comment by twistedpair** [comment]
Worth looking at how the autogenerated code did this....however, they did not do OverlayView. You can see their [Overlay Solution](http://code.google.com/p/gwt-google-apis/source/browse/trunk/maps/maps/src/com/google/gwt/maps/client/overlay/Overlay.java).

**Comment by branflake2267** [comment]
That link didnt work. It looks like it points at our overlay.

**Comment by branflake2267** [comment]
Looking at OverlayView.onAdd() in more detail, I see that method in the master, are you thinking that should be different, or did you add those?

**Comment by branflake2267** [comment]
Oh I see, those functions are closures. Yeah, I see what we need to add. I think I wrote some callbacks like that in street view or somewhere else. I can't remember.

**Comment by branflake2267** [comment]
Saving this example to look at later: http://james.lin.net.nz/2012/05/24/google-map-v3-overlayview-code-sample/

**Comment by branflake2267** [comment]
Another handy example we could use for testing: http://blog.mridey.com/2009/09/label-overlay-example-for-google-maps.html

**Comment by twistedpair** [comment]
Brandon, see the [Official Google OverlayView example](http://code.google.com/p/gwt-google-apis/source/browse/trunk/maps/maps/src/com/google/gwt/maps/client/overlay/Overlay.java).

Also, fixed that link to the overlay code in the generated project's [Overlay code.](http://code.google.com/p/gwt-google-apis/source/browse/trunk/maps/maps/src/com/google/gwt/maps/client/overlay/Overlay.java).

I'm just not sure if this won't cause a problem since it is an expected prototype, not just a callback. Would something like the following work?

``` java
public final void setOnAddCallback( Callback callback ) /*-{
    this.onAddCallback = callback;
    setOnAddCallbackImpl();
)-*/

public final native void setOnAddCallbackImpl() /*-{
    this.prototype.onAdd = @this.onAddImpl()();
)-*/

private void onAddImpl() {
    this.onAddCallback.run();
}
```

(pseudocode, too late to lookup the JNI syntax)

**Comment by branflake2267** [comment]
I'm not sure, I haven't done that way. I like to use a handler interface with the callback method. I use an anonymous function for this.onAdd() = anon func and then I use that function to call the interface handler method. But that might not be the best way, I'm just pulling off what I usually do.

**Comment by twistedpair** [comment]
My concern is why this is the only case of the Maps API specifying an interface rather than an implementation or callback. Perhaps these functions needed a higher performance? In that case, allowing the users to set a callback and then defining the function with it might be more inline with the original Maps API architecture.

**Comment by twistedpair** [comment]
Currently 5 (intentionally) failing tests due to this. Will try to finalize the callback handlers tonight so they pass.

**Comment by branflake2267** [comment]
Let me know if you need a hand on the handlers :)

**Comment by branflake2267** [comment]
I've started on the overlay view.
1. created a ground overlay example
2. working on a custom overlay example
3. working on the proto in OverlayView

**Comment by twistedpair** [comment]
We already have a demo. You can add to that. See the moon/mars showcase demo.

**Comment by branflake2267** [comment]
Good point. I'll use it for testing then merge it into the other when I'm done. :)
