### ISSUE TITLE
gwt-dev resolved through gwt-ajaxloader

### ISSUE THREAD

**Issue by rwl** [branflake2267/GWT-Maps-V3-Api#89]
I have tried the latest source, but I am still getting the error in #88 because the gwt-dev dependency is resolved through the dependency on `gwt-ajaxloader`. Perhaps an exclusion should be added and a ticket raised [here](http://code.google.com/p/gwt-google-apis/issues/list).

**Comment by twistedpair** [comment]
@rwl My apologies for the premature ticket closure.

The real question here is what's unique about your many POM dependencies compared to ours and others who have not experienced this issue. You said that it is triggered by the goal `gwt:run` and I must admit that I just use the _Run as > Web Application_ option in Eclipse.

It appears your issue is due to the transitive dependency of `gwt-dev` 2.0.3 from the [`google-apis-parent`](http://search.maven.org/#artifactdetails%7Ccom.google.gwt.google-apis%7Cgoogle-apis-parent%7C1%7Cpom) POM. However, when I view the _POM > Dependency Hierarchy_, it indicates:

> gwt-dev: 2.5.0 (managed from 2.0.3) [provided] (from compile)

Is this also the case for your project? It appears Maven correctly takes the newer version, so I wonder why it is not in the case of your use case.

**Comment by rwl** [comment]
My understanding is that dependency on `gwt-dev` is rarely necessary and should be avoided. The error I was seeing can be reproduced using the showcase by removing the `gwt-dev` dependency and the dependency management.

https://github.com/rwl/GWT-Maps-V3-Api/commit/e3e8115619152130a66c146332100e0bc85023e1

A temporary solution is to add `gwt-dev` exclusions, but ultimately I don't think `gwt-ajaxloader` should be dependent upon it.

https://github.com/rwl/GWT-Maps-V3-Api/commit/75e7506e419ef39967261d07d2d52b187b1763cc

**Comment by twistedpair** [comment]
Will add this to the FAQ I'm writing, but otherwise will soon close it as it is a matter with a dependency beyond the direct control of our own code base.

**Comment by twistedpair** [comment]
I believe this item is now closed, as far as we can. If it is still impacting you from the ambient HEAD, please shout out.
