### ISSUE TITLE
Wiki directions for using the api in a GWT project

### ISSUE THREAD

**Issue by branflake2267** [branflake2267/GWT-Maps-V3-Api#9]
I'd like to write up simple instructions on how to use this api in a GWT project.

**Comment by twistedpair** [comment]
Just add basic build instructions to https://github.com/branflake2267/GWT-Maps-V3-Api/wiki

I pushed the most recent jars from my personal Team City account out there. I've opened a Jira account with Sonatype to use their OSS maven repo so that we can get the project artifacts into the Central Repository.

I've opened a ticket par their instructions so that we can then remove the need to upload/download jars on the site, but there a GitHub API for that.

**Comment by twistedpair** [comment]
Unless anyone finds otherwise, the supplied instructions should be sufficient. Closing.
